### ISSUE TITLE
Ada_krylov missing

### ISSUE THREAD

**Issue by peekxc** [tchen-research/krylov_aware_trace#1]
In your [adaptive.ipynb](https://github.com/tchen-research/krylov_aware_trace/blob/1c4be5b44c866ffebeb9386ac925f6ad39091b70/adaptive.ipynb#L50), you call a function called `ada_krylov` which implements Alg. 4.1 from [your paper](https://arxiv.org/pdf/2205.01736), but I don't see the actual function definition anywhere.

**Comment by tchen01** [comment]
Thanks, I think I forgot to commit the file that had that code. I have just added it now and think it should be working. Please reopen the issue if it's not resolved and I will look into it more.

**Comment by tchen01** [comment]
Thanks, I think I forgot to commit the file that had that code. I have just added it now and think it should be working. Please reopen the issue if it's not resolved and I will look into it more.
